# -*- coding: utf-8 -*-
"""Graphical Data Representation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TlKIW5BkMHpPX0URtLvlFa_kNyv4ANQ

# **A Graphical Exploration of Barangay Catalina, Cauayan City, Isabela II**

---

# **A. Demography**

***1. Population***
"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings
    title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
    label_font = {'fontsize': 9, 'color': '#8A2BE2'}

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 5)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4')
    ax1.tick_params(axis='y', labelcolor='#8A2BE2')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.5, int(yval), ha='center', va='bottom', color='#8A2BE2', fontsize=8)

    # Pie chart
    total_population = 91
    percentages = [(v / total_population) * 100 for v in values]
    ax2.pie(values, labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# DEMOGRAPHY DATA (Pastel Palette)
categories = ["Children 0-5 \nyears old", "Children 6-12 \nyears old", "Children 13-16 \nyears old", "Children 17+ \nyears old"]
# Known values
value_0_5 = 8
value_6_12 = 19
value_13_16 = 11
# Calculate 17+ years old
total_population = 91
value_17_plus = total_population - (value_0_5 + value_6_12 + value_13_16)

values = [value_0_5, value_6_12, value_13_16, value_17_plus]
# pastel colors
bar_colors = ["#FDEF81", "#FBCFE0", "#A5F1E9", "#D8A7D8"]
pie_colors = ["#FDEF81", "#FBCFE0", "#A5F1E9", "#D8A7D8"]

plot_bar_pie("Population \n Total Population = 91", categories, values, bar_colors, pie_colors)

"""***2. Population by Gender***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings
    title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
    label_font = {'fontsize': 9, 'color': '#8A2BE2'}

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 5)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4')
    ax1.tick_params(axis='y', labelcolor='#8A2BE2')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.5, int(yval), ha='center', va='bottom', color='#8A2BE2', fontsize=8)

    # Pie chart
    total_population = sum(values)
    percentages = [(v / total_population) * 100 for v in values]
    ax2.pie(values, labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# GENDER DATA (Pastel Palette)
categories = ["Male", "Female"]
values = [47, 44]
# Light pastel blue and pastel pink
bar_colors = ["#ADD8E6", "#FFB6C1"]
pie_colors = ["#ADD8E6", "#FFB6C1"]

plot_bar_pie("Population by Gender \nTotal Population = 91", categories, values, bar_colors, pie_colors)

"""***3. Health and Nutrition***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors)
    ax1.set_title(title)
    ax1.set_ylabel("Population Magnitude")
    ax1.set_ylim(0, max(values) + 2)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center')
    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.2, int(yval), ha='center', va='bottom')

    # Pie chart
    ax2.pie(values, labels=categories, autopct='%1.1f%%', startangle=140, colors=pie_colors)
    ax2.set_title("Percentage Distribution")

    plt.tight_layout()
    plt.show()

# HEALTH AND NUTRITION DATA
categories = ["Died (Pregnancy-related)", "Malnourished (0-5 yrs)"]
values = [0, 0]
if sum(values) > 0:
    bar_colors = ["#f9a825", "#ffca28"]
    pie_colors = ["#f9a825", "#ffca28"]
    plot_bar_pie("Health and Nutrition", categories, values, bar_colors, pie_colors)
else:
  print("Health and Nutrition: No data display (all zero).")

"""***4. Housing***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings
    title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
    label_font = {'fontsize': 9, 'color': '#8A2BE2'}

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 2)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4')
    ax1.tick_params(axis='y', labelcolor='#8A2BE2')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.2, int(yval), ha='center', va='bottom', color='#8A2BE2', fontsize=8)

    # Pie chart
    total_population = 22
    percentages = [(v / total_population) * 100 for v in values]
    ax2.pie(values, labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# HOUSING DATA
categories = ["Households living in \nmakeshift housing", "Households who are \ninformal settlers"]
values = [0, 9]
# pastel colors
bar_colors = ["#FDEF81", "#FBCFE0"]
pie_colors = ["#FDEF81", "#FBCFE0"]

plot_bar_pie("Housing \n Total Household = 22", categories, values, bar_colors, pie_colors)

"""***5. Water and Sanitation***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, fontsize=13, fontweight='bold', color='#FF69B4')
    ax1.set_ylabel("Population Magnitude", fontsize=11, color='#8A2BE2')
    ax1.set_ylim(0, max(values) + 2)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', fontsize=10, color='#FF69B4')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    total_population = 22

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.3,
                 f"{int(yval)}", ha='center', va='bottom', fontsize=10, color='#8A2BE2')

    # Pie chart
    adjusted_values = [(v / total_population) for v in values]
    percentages = [(v / total_population) * 100 for v in values]

    ax2.pie(adjusted_values, labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'fontsize': 9, 'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", fontsize=13, fontweight='bold', color='#FF69B4')
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# WATER AND SANITATION DATA (Pastel Palette)
categories = [
    "Households without access\nto safe water",
    "Households without access\nto sanitary toilet facility"
]
values = [3, 0]

# Using the same pastel colors
bar_colors = ['#FDEF81', '#FBCFE0']
pie_colors = ['#FDEF81', '#FBCFE0']

plot_bar_pie("Water and Sanitation \n Total Household = 22", categories, values, bar_colors, pie_colors)

"""***6. Basic Education***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings
    title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
    label_font = {'fontsize': 9, 'color': '#8A2BE2'}

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 5)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4')
    ax1.tick_params(axis='y', labelcolor='#8A2BE2')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.5, int(yval), ha='center', va='bottom', color='#8A2BE2', fontsize=8)

    # Pie chart
    total_population = 91  # Shared total
    percentages = [(v / total_population) * 100 for v in values]
    ax2.pie(values, labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# BASIC EDUCATION DATA
categories = [
    "Children 6-12 years old \nnot attending elementary",
    "Children 13-16 years old \nnot attending high school"
]
values = [5, 7]
# pastel colors
bar_colors = ["#A5F1E9", "#D8A7D8"]
pie_colors = ["#A5F1E9", "#D8A7D8"]

plot_bar_pie("Basic Education \n Total Population = 91", categories, values, bar_colors, pie_colors)

"""***7. Income and Livelihood***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings (pastel style, smaller for readability)
    title_font = {'fontsize': 11, 'fontweight': 'bold', 'color': '#FF69B4'}  # pastel pink
    label_font = {'fontsize': 8, 'color': '#8A2BE2'}  # pastel violet

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 5)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4', fontsize=7)
    ax1.tick_params(axis='y', labelcolor='#8A2BE2', labelsize=7)
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.5, int(yval),
                 ha='center', va='bottom', color='#8A2BE2', fontsize=7)

    # Pie chart
    total_population = sum(values)
    percentages = [(v / 22) * 100 for v in values]  # Calculate percentage by dividing by 22
    wedges, texts = ax2.pie(
        values,
        labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
        startangle=140,
        colors=pie_colors,
        textprops={'color': '#8A2BE2', 'fontsize': 7}
    )
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    # Move the pie chart a little lower
    box = ax2.get_position()
    ax2.set_position([box.x0, box.y0 - 0., box.width, box.height])

    plt.tight_layout()
    plt.show()

# INCOME AND LIVELIHOOD DATA (Pastel Palette)
categories = [
    "Households with income \nbelow poverty threshold",
    "Households with income \nbelow food threshold",
    "Households who \nexperienced food shortage",
    "Unemployed members \nof the labor force"
]
values = [15, 10, 2, 5]

# PASTEL colors (same style as demography)
bar_colors = ["#FDEF81", "#FBCFE0", "#A5F1E9", "#D8A7D8"]
pie_colors = bar_colors

plot_bar_pie("Income and Livelihood\nTotal Household = 22", categories, values, bar_colors, pie_colors)

"""***8. Peace and Order***"""

import matplotlib.pyplot as plt

def plot_bar_pie(title, categories, values, bar_colors, pie_colors, total_population):
    x_pos = range(len(categories))
    bar_width = 0.6

    # Font settings
    title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
    label_font = {'fontsize': 9, 'color': '#8A2BE2'}

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    bars = ax1.bar(x_pos, values, width=bar_width, color=bar_colors, edgecolor='white', linewidth=1.5)
    ax1.set_title(title, **title_font)
    ax1.set_ylabel("Population Magnitude", **label_font)
    ax1.set_ylim(0, max(values) + 2)
    ax1.set_xticks(x_pos)
    ax1.set_xticklabels(categories, rotation=0, ha='center', color='#FF69B4')
    ax1.tick_params(axis='y', labelcolor='#8A2BE2')
    ax1.grid(axis='y', linestyle='--', alpha=0.5)

    for bar in bars:
        yval = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.2, int(yval), ha='center', va='bottom', color='#8A2BE2', fontsize=8)

    # Adjusted Pie Chart computation
    adjusted_values = [(v / total_population) for v in values]
    percentages = [(v / total_population) * 100 for v in values]

    # Pie chart
    ax2.pie(adjusted_values,
            labels=[f"{cat}\n{perc:.1f}%" for cat, perc in zip(categories, percentages)],
            startangle=140, colors=pie_colors, textprops={'color': '#8A2BE2'})
    ax2.set_title("Percentage Distribution", **title_font)
    ax2.axis('equal')

    plt.tight_layout()
    plt.show()

# PEACE AND ORDER DATA (Blue Palette)
categories = ["Victim of crime"]
values = [1]
bar_colors = ["#D8A7D8"]
pie_colors = ["#D8A7D8"]

# Set the correct TOTAL population here!
total_population = 22

plot_bar_pie("Peace and Order \n Total Household = 22", categories, values, bar_colors, pie_colors, total_population)

"""# ***B. Filipino Labor Force***

***1. Overseas Filipino Workers***
"""

import matplotlib.pyplot as plt
import numpy as np

# Categories
categories = ['OFWs', 'Non-working Overseas']

# Values by gender
male = [1, 1]
female = [1, 1]

# Bar width and positions
x = np.arange(len(categories))
width = 0.35

# Colors
colors = ['#B6E2FD', '#FBCFE0']

# Fonts
title_font = {'fontsize': 12, 'fontweight': 'bold', 'color': '#FF69B4'}
label_font = {'fontsize': 9, 'color': '#8A2BE2'}

# Create single bar chart
fig, ax1 = plt.subplots(figsize=(6, 5))

# Bar chart
ax1.bar(x - width/2, male, width, label='Male', color=colors[0])
ax1.bar(x + width/2, female, width, label='Female', color=colors[1])
ax1.set_xlabel('Category', **label_font)
ax1.set_ylabel('Count', **label_font)
ax1.set_title('Overseas Filipinos by Gender \nTotal Population = 95', **title_font)
ax1.set_xticks(x)
ax1.set_xticklabels(categories, color='#FF69B4')
ax1.legend()
ax1.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""***2. Members of the Labor Force***"""

import matplotlib.pyplot as plt

# Data
categories = ['Employed', 'Unemployed']
male_counts = [22, 4]
female_counts = [10, 1]
x = range(len(categories))  # x locations for the bars

# Bar settings
bar_width = 0.35

# Plotting
fig, ax1 = plt.subplots(figsize=(6, 5))  # Single plot

# Bar chart
ax1.bar([p - bar_width/2 for p in x], male_counts, bar_width, label='Male', color='#B6E2FD')
ax1.bar([p + bar_width/2 for p in x], female_counts, bar_width, label='Female', color='#FBCFE0')

# Labels and styling for bar chart
ax1.set_xlabel('Labor Force Category', fontsize=10, color='#8A2BE2')
ax1.set_ylabel('Number of People', fontsize=10, color='#8A2BE2')
ax1.set_title('Employed and Unemployed Labor Force by Gender \nTotal Population = 95', fontsize=12, fontweight='bold', color='#FF69B4')
ax1.set_xticks(x)
ax1.set_xticklabels(categories, color='#FF69B4')
ax1.legend()
ax1.grid(axis='y', linestyle='--', alpha=0.5)

# Layout adjustment
plt.tight_layout()
plt.show()

"""# ***C. Priority Sectors***

***1. Persons With Disability (PWD)***
"""

import matplotlib.pyplot as plt

# Data for Persons with Disability (PWD) by Gender
genders = ['Male', 'Female']
pwd_counts = [2, 0]  # [Male PWD, Female PWD]
x = range(len(genders))  # x locations for the bars

# Bar settings
bar_width = 0.6

# Create single plot
fig, ax1 = plt.subplots(figsize=(5, 4))

# Bar chart
ax1.bar(x, pwd_counts, bar_width, color=['#B6E2FD', '#FBCFE0'])

# Labels and styling for bar chart
ax1.set_xlabel('Gender', fontsize=10, color='#8A2BE2')
ax1.set_ylabel('Number of Persons with Disability (PWD)', fontsize=10, color='#8A2BE2')
ax1.set_title('PWD by Gender \nTotal Population = 95', fontsize=12, fontweight='bold', color='#FF69B4')
ax1.set_xticks(x)
ax1.set_xticklabels(genders, color='#FF69B4')
ax1.grid(axis='y', linestyle='--', alpha=0.5)

# Layout
plt.tight_layout()
plt.show()

"""***2. Senior Citizens With ID***"""

import matplotlib.pyplot as plt

# Data for Senior citizens with ID by Gender
genders = ['Male', 'Female']
pwd_counts = [2, 4]
x = range(len(genders))

# Bar settings
bar_width = 0.6

# Create single plot
fig, ax1 = plt.subplots(figsize=(5, 4))

# Bar chart
ax1.bar(x, pwd_counts, bar_width, color=['#B6E2FD', '#FBCFE0'])

# Labels and styling for bar chart
ax1.set_xlabel('Gender', fontsize=10, color='#8A2BE2')
ax1.set_ylabel('Number of Senior Citizens with ID', fontsize=10, color='#8A2BE2')
ax1.set_title('Senior Citizens with ID by Gender \nTotal Population = 95', fontsize=12, fontweight='bold', color='#FF69B4')
ax1.set_xticks(x)
ax1.set_xticklabels(genders, color='#FF69B4')
ax1.grid(axis='y', linestyle='--', alpha=0.5)
ax1.set_xlim([-0.5, len(genders) - 0.5])

# Final layout
plt.tight_layout()
plt.show()

"""***3. Solo Parents***"""

import matplotlib.pyplot as plt

# Data for Solo Parents by Gender
genders = ['Male', 'Female']
pwd_counts = [2, 0]
x = range(len(genders))

# Bar settings
bar_width = 0.6

# Create single plot
fig, ax1 = plt.subplots(figsize=(5, 4))

# Bar chart
ax1.bar(x, pwd_counts, bar_width, color=['#B6E2FD', '#FBCFE0'])

# Labels and styling for bar chart
ax1.set_xlabel('Gender', fontsize=10, color='#8A2BE2')
ax1.set_ylabel('Number of Solo Parents', fontsize=10, color='#8A2BE2')
ax1.set_title('Solo Parents by Gender \nTotal Population = 95', fontsize=12, fontweight='bold', color='#FF69B4')
ax1.set_xticks(x)
ax1.set_xticklabels(genders, color='#FF69B4')
ax1.grid(axis='y', linestyle='--', alpha=0.5)
ax1.set_xlim([-0.5, len(genders) - 0.5])

# Final layout
plt.tight_layout()
plt.show()

"""# **D. Household Engagement in Livelihood Activities**

***1. Household Engagement in Agriculture***
"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [31.82, 68.18]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [7, 15]
ax1.bar(categories, households, color=["#FDEF81", "#FBCFE0"])
ax1.set_title('Households Engaged in Agriculture \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FDEF81", "#FBCFE0"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***2. Households Engagement in Livestock Raising***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [22.73, 77.27]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [5, 17]
ax1.bar(categories, households, color=["#A5F1E9", "#D8A7D8"])
ax1.set_title('Households Engaged in Livestock Raising  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#A5F1E9", "#D8A7D8"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***3. Households Engagement in Fishing***

"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [0.00, 100.00]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [0, 22]
ax1.bar(categories, households, color=['#FF69B4', '#8A2BE2'])
ax1.set_title('Households Engaged in Fishing  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ['#FF69B4', '#8A2BE2']
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""#**E. Household Experiences of Environmental and Utility-Related Calamities**

***1. Household that Experienced More Frequent Flooding***
"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Experienced', 'Not Experienced']
proportions =  [68.18, 31.82]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [15, 7]
ax1.bar(categories, households, color=["#DCEDC8", "#FFB3BA"])
ax1.set_title('Households Experienced More Frequent Flooding  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#DCEDC8", "#FFB3BA"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***2. Household that Experienced More Frequent Droughts***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Experienced', 'Not Experienced']
proportions = [45.45, 54.55]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [10, 12]
ax1.bar(categories, households, color=["#E2BAFF", "#FFF9C4"])
ax1.set_title('Households Experienced More Frequent Drought  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#E2BAFF", "#FFF9C4"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***3. Household that Experienced Decrease in Water Supply***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Experienced', 'Not Experienced']
proportions = [4.55, 95.45]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [1, 21]
ax1.bar(categories, households, color=["#FFDFBA", "#C5CAE9"])
ax1.set_title('Households Experienced Decrease in Water Supply  \n\nTotal Household: 22' )
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFDFBA", "#C5CAE9"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***4. Household that Experienced More Frequent Brownouts***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Experienced', 'Not Experienced']
proportions = [59.09, 40.91]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [13, 9]
ax1.bar(categories, households, color=["#ADD8E6", "#FFB6C1"])
ax1.set_title('Households Experienced More Frequent Brownouts  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#ADD8E6", "#FFB6C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""***5. Household that Experienced Moving out or Leaving Previous Dwelling Unit Because of any Calamity***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Experienced', 'Not Experienced']
proportions = [36.36, 63.64]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [8,14]
ax1.bar(categories, households, color=["#FFD1DC", "#C8E6C9"])
ax1.set_title('Households Experienced Moving out/ Leaving Previous \nDwelling Unit Because of any Calamity  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFD1DC", "#C8E6C9"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Household Engagement')

plt.tight_layout()
plt.show()

"""# ***F. Household Engagement in Entrepreneurial Activity***

***1. Engaged in Crop Farming and Gardening***
"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [31.82, 68.18]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [7, 15]
ax1.bar(categories, households, color=["#b1eab9", "#ccf2e6"])
ax1.set_title('Engaged in Crop Farming and Gardening  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#b1eab9", "#ccf2e6"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***2. Engaged in Livestock/Poultry***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [22.73, 77.27]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [5, 17]
ax1.bar(categories, households, color=["#b1eab9", "#B4B5EE"])
ax1.set_title('Households Engaged in Livestock/Poultry  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#b1eab9", "#B4B5EE"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***3. Engaged in Fishing***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Fishing  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***4. Engaged in Forestry***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Forestry  \n\nTotal Household: 22')

ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***5. Engaged in Wholesale/Retail***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [9.09, 90.91]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [5, 17]
ax1.bar(categories, households, color=["#b1eab9", "#F8B3CA"])
ax1.set_title('Households Engaged in Wholesale/Retail  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#b1eab9", "#F8B3CA"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***6. Engaged in Manufacturing***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Manufacturing  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***7. Engaged in Community, Social and Personal Service***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Community, Social, And Personal Service  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***8. Engaged in Transportation, Storage and Communication***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Transporation, Storage & Communication  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***9. Engaged in Mining and Quarrying***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Mining & Quarrying  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***10. Engaged in Contruction***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [4.55, 95.45]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [1, 21]
ax1.bar(categories, households, color=["#CFEFBA", "#FAFFBA"])
ax1.set_title('Households Engaged in Construction  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#CFEFBA", "#FAFFBA"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""***11. Other Activies***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FFE7C1", "#FFE7C1"])
ax1.set_title('Households Engaged in Other Activities  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE7C1", "#FFE7C1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Entrepreneurial Activity')

plt.tight_layout()
plt.show()

"""# ***G. Household Engagement by Type of Garbage Collection***

***1. Garbage Collected***
"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [90.91, 9.09]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [20, 2]
ax1.bar(categories, households, color=["#E4E2CF", "#ECEAE4"])
ax1.set_title('Garbage Collected \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#E4E2CF", "#ECEAE4"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***2. Garbage Burned***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [9.09, 90.91]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [2, 20]
ax1.bar(categories, households, color=["#DEEEEE", "#91BABB"])
ax1.set_title('Garbage Burned \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#DEEEEE", "#91BABB"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***3. Garbage Composted***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [31.82, 68.18]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [7, 13]
ax1.bar(categories, households, color=["#F39FA6", "#FCDCCF"])
ax1.set_title('Garbage Composted \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#F39FA6", "#FCDCCF"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***4. Garbage Recycled***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [27.27, 72.73]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [6, 14]
ax1.bar(categories, households, color=["#FFE5A4", "#FFEFCD"])
ax1.set_title('Garbage Recycled \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FFE5A4", "#FFEFCD"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***5. Garbage Segregated***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [45.45, 54.55]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [12, 10]
ax1.bar(categories, households, color=["#E3D8D0", "#CCBEB7"])
ax1.set_title('Garbage Segregated \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#E3D8D0", "#CCBEB7"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***6. Garbage Dumped to Closed Pit***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [18.18, 81.82]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [4, 18]
ax1.bar(categories, households, color=["#FBB9A6", "#F6A294"])
ax1.set_title('Garbage Dumped to Closed Pit \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FBB9A6", "#F6A294"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***7. Garbage Dumped to Open Pit***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
proportions = [45.45, 54.55]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
households = [10, 12]
ax1.bar(categories, households, color=["#F9D1C3", "#DFABA2"])
ax1.set_title('Garbage Dumped to Open Pit \nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#F9D1C3", "#DFABA2"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()

"""***8. Other Waste Management***"""

import matplotlib.pyplot as plt

# Data from the table
categories = ['Engaged', 'Not Engaged']
households = [0, 22]  # Number of households in each category

# Calculate proportions
total_households = sum(households)
proportions = [h / total_households * 100 for h in households]  # Proportion in percentage

# Set up figure and subplots side by side
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Bar graph
ax1.bar(categories, households, color=["#FCF5E1", "#FCF5E1"])
ax1.set_title('Other Waste Management  \n\nTotal Household: 22')
ax1.set_ylabel('Number of Households')
ax1.set_ylim(0, max(households) + 2)

# Pie chart
colors = ["#FCF5E1", "#FCF5E1"]
ax2.pie(
    proportions,
    labels=categories,
    autopct='%.2f%%',
    startangle=90,
    colors=colors
)
ax2.set_title('Proportion of Households by Type of Garbage Collection')

plt.tight_layout()
plt.show()